language: node_js

node_js:
  - node
  - lts/*

cache:
  directories:
    - ".yarn-offline-mirror"

before_install:
  - yarn config set yarn-offline-mirror ".yarn-offline-mirror"
  - yarn config set yarn-offline-mirror-pruning true

install:
  yarn --prefer-offline

script:
  yarn run test && test -z "$(git status --porcelain)"
