on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2.4.0'
        with:
          submodules: 'recursive'
      - uses: 'cachix/install-nix-action@v17'
        with:
          nix_path: 'nixpkgs=channel:nixpkgs-unstable'
      - run: |
          nix-shell --command 'yarn && yarn run test'

          if ! test -z "$(git status --porcelain)"; then
            echo "There were untracked files after running linters, please check the output of git status"
            git status
            exit 1
          fi
      - run: |
          nix-shell --arg nodeVersion '"nodejs-14_x"' --command 'yarn && yarn run test'
      - run: |
          nix-shell --arg nodeVersion '"nodejs-16_x"' --command 'yarn && yarn run test'
